version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: voice_bot_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  bot:
    build: .
    container_name: voice_ai_bot
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./documents:/app/documents
    restart: unless-stopped

volumes:
  redis_data: